using System.Text;
using EnterpriseArchAgent.Core.Abstractions;
using EnterpriseArchAgent.Core.Agents;
using EnterpriseArchAgent.Core.Domain;

namespace EnterpriseArchAgent.Core.Application;

/// <summary>
/// Runs the agents as a sequential handoff pipeline: each agent receives the original
/// brief plus everything the previous agents produced, so later agents (Security, ADR,
/// Cost) reason about the actual architecture rather than starting from scratch.
///
/// This is the orchestration layer of a multi-agent system — the agents are specialists;
/// the orchestrator is the "lead architect" routing context between them.
/// </summary>
public sealed class ArchitectureOrchestrator
{
    private readonly IAgentRunner _runner;

    public ArchitectureOrchestrator(IAgentRunner runner) => _runner = runner;

    public async Task<ArchitecturePackage> GenerateAsync(
        ArchitectureRequest request, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(request.Brief))
            throw new ArgumentException("Brief is required.", nameof(request));

        var outputs = new List<AgentOutput>();

        // The running context handed from one agent to the next.
        var context = new StringBuilder();
        context.AppendLine("# Project brief");
        context.AppendLine(request.Brief);
        if (!string.IsNullOrWhiteSpace(request.Constraints))
        {
            context.AppendLine();
            context.AppendLine("# Constraints");
            context.AppendLine(request.Constraints);
        }

        foreach (var spec in ArchitectureAgentCatalog.All)
        {
            ct.ThrowIfCancellationRequested();

            var input =
                $"{context}\n\n# Your task\n" +
                $"Acting as the {spec.Name}, produce the '{spec.Title}' section described in your instructions.";

            var result = await _runner.RunAsync(spec, input, ct);
            outputs.Add(new AgentOutput(spec.Role, spec.Title, result));

            // Hand this section forward so downstream agents can build on it.
            context.AppendLine();
            context.AppendLine($"# {spec.Title} (by {spec.Name})");
            context.AppendLine(result);
        }

        return new ArchitecturePackage(
            request.Brief, outputs, BuildDocument(request, outputs), DateTimeOffset.UtcNow);
    }

    /// <summary>Assemble all sections into one cohesive Markdown design document.</summary>
    private static string BuildDocument(ArchitectureRequest request, IReadOnlyList<AgentOutput> outputs)
    {
        var doc = new StringBuilder();
        doc.AppendLine("# Architecture Design Package");
        doc.AppendLine();
        doc.AppendLine($"> Generated by the Enterprise Architecture Agent on {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm} UTC.");
        doc.AppendLine();
        doc.AppendLine("## Brief");
        doc.AppendLine(request.Brief);
        if (!string.IsNullOrWhiteSpace(request.Constraints))
        {
            doc.AppendLine();
            doc.AppendLine("**Constraints:** " + request.Constraints);
        }
        doc.AppendLine();
        foreach (var o in outputs)
        {
            doc.AppendLine($"## {o.Title}");
            doc.AppendLine();
            doc.AppendLine(o.Content);
            doc.AppendLine();
        }
        return doc.ToString();
    }
}
